### ISSUE TITLE
How to include this package?

### ISSUE THREAD

**Issue by pranny** [nate-strauser/meteor-jquery.scrollTo#3]
Apologies, if this sounds noob. I am new, and facing an issue. I am unable to add the package to my meteor app. The package is added by

```
meteor add natestrauser:jquery-scrollto
```

How do I include this in my app.js? Upon doing the following

```
angular
  .module('Octo', [
    'angular-meteor',
    'ionic',
    'jquery.scrollto'
  ]);
```

I get the error stating

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module Octo due to:
Error: [$injector:modulerr] Failed to instantiate module jquery.scrollto due to:
Error: [$injector:nomod] Module 'jquery.scrollto' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument
```

**Comment by nate-strauser** [comment]
i don't think this can be used as a module like that - this is only going to expose a new method on `$(...)` - see https://github.com/flesler/jquery.scrollTo
